#%RAML 1.0 ResourceType

usage: Apply this resource type to any resource has not been implmented

uses:



get:
  description: Returns a an error that says not implemented
  responses:
    405:
      body:
        application/json:
          type: <<unimplemented-error>>

post:
  description: Returns a an error that says not implemented
  responses:
    405:
      body:
        application/json:
          type: <<unimplemented-error>>

put:
  description: Returns a an error that says not implemented
  responses:
    405:
      body:
        application/json:
          type: <<unimplemented-error>>

patch:
  description: Returns a an error that says not implemented
  responses:
    405:
      body:
        application/json:
          type: <<unimplemented-error>>

delete:
  description: Returns a an error that says not implemented
  responses:
    405:
      body:
        application/json:
          type: <<unimplemented-error>>
